### ISSUE TITLE
Linea del Tiempo.

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-7-Nancy-0714#1]
Actividad 1.
Nancy Olivera Santiago.
Grupo: 1BS.
![Linea del Tiempo-Nancy Os](https://user-images.githubusercontent.com/112412856/196048834-40c5a152-170d-4bf5-b2ec-35a0227147cd.png)

**Comment by Blanca-estela-valerio-rivero** [comment]
tiene 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
